import React from 'react'
import Productcard from './Productcard'

const ProductComponentShowAgro = () => {
  return (
    <div className=' '>
        <h1 className="text-center  mt-[120px] md:mt-[40px] text-[40px]   md:text-[50px]  font-thin uppercase opacity-75 hover:font-normal duration-700 text-zinc-900   ">Agro Products</h1>
    <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-7 my-14
    px-5 md:px-0'>
        <Productcard image={'/vamrap.jpg'} name={'Visakha amra pickle'} p={"Visakha Consumer Products prides itself on crafting pickles that are made fresh, ensuring a delightful taste experience without the use of added preservatives. Each jar is filled with high-quality ingredients, capturing the authentic flavors of traditional recipes, allowing you to enjoy the natural goodness and vibrant taste in every bite. Visakha Consumer Products is dedicated to delivering pickles that embody freshness and quality. Our pickles are prepared using only the finest ingredients, ensuring that no added preservatives compromise their natural flavor. Each batch is meticulously crafted to maintain the authentic taste and texture, providing a delightful addition to any meal. With Visakha pickles, you can relish the true essence of homemade goodness, making every dining experience special. "} price={"340"} discountedprice={"240"} />
          <Productcard image={'/vap.jpg'} name={'Visakha amla pickle'} p={"Visakha Consumer Products prides itself on crafting pickles that are made fresh, ensuring a delightful taste experience without the use of added preservatives. Each jar is filled with high-quality ingredients, capturing the authentic flavors of traditional recipes, allowing you to enjoy the natural goodness and vibrant taste in every bite. Visakha Consumer Products is dedicated to delivering pickles that embody freshness and quality. Our pickles are prepared using only the finest ingredients, ensuring that no added preservatives compromise their natural flavor. Each batch is meticulously crafted to maintain the authentic taste and texture, providing a delightful addition to any meal. With Visakha pickles, you can relish the true essence of homemade goodness, making every dining experience special. "} price={"1249"} discountedprice={"900"} />
          <Productcard image={'/vgarlic.jpg'} name={"Visakha garlic pickle"} p={"Visakha Consumer Products prides itself on crafting pickles that are made fresh, ensuring a delightful taste experience without the use of added preservatives. Each jar is filled with high-quality ingredients, capturing the authentic flavors of traditional recipes, allowing you to enjoy the natural goodness and vibrant taste in every bite. Visakha Consumer Products is dedicated to delivering pickles that embody freshness and quality. Our pickles are prepared using only the finest ingredients, ensuring that no added preservatives compromise their natural flavor. Each batch is meticulously crafted to maintain the authentic taste and texture, providing a delightful addition to any meal. With Visakha pickles, you can relish the true essence of homemade goodness, making every dining experience special. "} price={"1249"} discountedprice={"800"} />
          <Productcard image={'/vgp.jpg'} name={'Visakha ginger pickle'} p={"Visakha Consumer Products prides itself on crafting pickles that are made fresh, ensuring a delightful taste experience without the use of added preservatives. Each jar is filled with high-quality ingredients, capturing the authentic flavors of traditional recipes, allowing you to enjoy the natural goodness and vibrant taste in every bite. Visakha Consumer Products is dedicated to delivering pickles that embody freshness and quality. Our pickles are prepared using only the finest ingredients, ensuring that no added preservatives compromise their natural flavor. Each batch is meticulously crafted to maintain the authentic taste and texture, providing a delightful addition to any meal. With Visakha pickles, you can relish the true essence of homemade goodness, making every dining experience special. "} price={"949"} discountedprice={"600"} />
         <Productcard image={'/vkp.jpg'} name={'Visakha kathal pickle'} p={"Visakha Consumer Products prides itself on crafting pickles that are made fresh, ensuring a delightful taste experience without the use of added preservatives. Each jar is filled with high-quality ingredients, capturing the authentic flavors of traditional recipes, allowing you to enjoy the natural goodness and vibrant taste in every bite. Visakha Consumer Products is dedicated to delivering pickles that embody freshness and quality. Our pickles are prepared using only the finest ingredients, ensuring that no added preservatives compromise their natural flavor. Each batch is meticulously crafted to maintain the authentic taste and texture, providing a delightful addition to any meal. With Visakha pickles, you can relish the true essence of homemade goodness, making every dining experience special. "} price={"1249"} discountedprice={"850"} />
         <Productcard image={'/vlp.jpg'} name={'Visakha lemon pickle'} p={"Visakha Consumer Products prides itself on crafting pickles that are made fresh, ensuring a delightful taste experience without the use of added preservatives. Each jar is filled with high-quality ingredients, capturing the authentic flavors of traditional recipes, allowing you to enjoy the natural goodness and vibrant taste in every bite. Visakha Consumer Products is dedicated to delivering pickles that embody freshness and quality. Our pickles are prepared using only the finest ingredients, ensuring that no added preservatives compromise their natural flavor. Each batch is meticulously crafted to maintain the authentic taste and texture, providing a delightful addition to any meal. With Visakha pickles, you can relish the true essence of homemade goodness, making every dining experience special. "} price={"1249"} discountedprice={"850"} />
         <Productcard image={'/vmp.jpg'} name={'Visakha mango pickle'} p={"Visakha Consumer Products prides itself on crafting pickles that are made fresh, ensuring a delightful taste experience without the use of added preservatives. Each jar is filled with high-quality ingredients, capturing the authentic flavors of traditional recipes, allowing you to enjoy the natural goodness and vibrant taste in every bite. Visakha Consumer Products is dedicated to delivering pickles that embody freshness and quality. Our pickles are prepared using only the finest ingredients, ensuring that no added preservatives compromise their natural flavor. Each batch is meticulously crafted to maintain the authentic taste and texture, providing a delightful addition to any meal. With Visakha pickles, you can relish the true essence of homemade goodness, making every dining experience special. "} price={"1249"} discountedprice={"850"} />
      
    </div>
    </div>
  )
}

export default ProductComponentShowAgro
