import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import store from "./store/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Visakha consumer products",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
